say:
  name: Zalo TTS Say
  description: Phát giọng nói bằng Zalo TTS
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: media_player
    message:
      required: true
      example: "Chào mừng anh đã về nhà"
    voice:
      example: 1
    speed:
      example: 1.0
